### ISSUE TITLE
Request to update README

### ISSUE THREAD

**Issue by axinhouzilaoyue** [qdeconinck/minitopo#5] opened 2021-10-06 09:33 UTC
Hello, I have been trying to use this project for mpquic testing recently. When can you update README? I hope I can get your help. Thank you. This is my email address: axin@bupt.edu.cn

**Comment by qdeconinck** [comment] 2021-10-19 07:35
This is actually a duplicate of #4. I still didn't find the time to write some doc, but feel free to start the work and I would be happy to review any PR.

**Closed as completed by qdeconinck** 2021-10-19 07:35 UTC
